steps:
  - label: "Run tests"
    command: "bundle install"
    command: "yarn"
    command: "bundle exec rake db:setup"
    command: "bundle exec rake db:schema:load"
    wait
    command: "bundle exec rake test"
    command: "bundle exec rake test:system"