steps:
  - label: "Install dependencies"
    commands: 
      - "bundle install"
      - "yarn"

  - wait

  - label: "Setup database"
    commands: 
      - "bundle exec rake db:setup" 
      - "bundle exec rake db:schema:load"

  - wait

  - label: "Test"
    commands: 
      - "bundle exec rake test" 
      - "bundle exec rake test:system"

  # - label: "Deploy"
  #   commands: 
  #     - "heroku git:remote --app stride-catcher"
  #     - "git push heroku "$$BUILDKITE_COMMIT":main"